train: /home/andrew/works/shpad_add/Detection-of-welding-seams/archive/train_images
val: /home/andrew/works/shpad_add/Detection-of-welding-seams/archive/valid_images


nc: 6


names: 
  0: "crazing"
  1: "inclusion"
  2: "patches"
  3: "pitted_surface"
  4: "rolled-in"
  5: "scratches"

