wandb_version: 1

learning_rate:
  desc: null
  value: 0.02
architecture:
  desc: null
  value: CNN
dataset:
  desc: null
  value: CIFAR-100
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.17.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1718310318
    t:
      1:
      - 1
      - 41
      - 55
      - 105
      2:
      - 1
      - 41
      - 55
      - 105
      3:
      - 16
      - 23
      4: 3.9.19
      5: 0.17.1
      8:
      - 1
      - 5
      13: linux-x86_64
