wandb_version: 1

data:
  desc: null
  value: new_train.yaml
epochs:
  desc: null
  value: 40
batch_size:
  desc: null
  value: 100
run_name:
  desc: null
  value: yolov10x_custom
_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.17.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1718384240
    t:
      1:
      - 1
      - 41
      - 55
      - 105
      3:
      - 16
      - 23
      4: 3.9.19
      5: 0.17.1
      8:
      - 1
      - 5
      13: linux-x86_64
